<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="1" failed="2" total="5" passed="2">
  <reporter-output>
  </reporter-output>
  <suite name="testNG Framework" duration-ms="4334" started-at="2018-02-28T05:08:09Z" finished-at="2018-02-28T05:08:14Z">
    <groups>
    </groups>
    <test name="chrome test" duration-ms="4281" started-at="2018-02-28T05:08:09Z" finished-at="2018-02-28T05:08:14Z">
      <class name="tests.skip">
        <test-method status="SKIP" signature="goingToSkip()[pri:0, instance:tests.skip@7f0eb4b4]" name="goingToSkip" duration-ms="1" started-at="2018-02-28T00:08:13Z" finished-at="2018-02-28T00:08:13Z">
          <exception class="org.testng.SkipException">
            <message>
              <![CDATA[Skipping because this test is no longer needed!!]]>
            </message>
            <full-stacktrace>
              <![CDATA[org.testng.SkipException: Skipping because this test is no longer needed!!
	at tests.skip.goingToSkip(skip.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- org.testng.SkipException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- goingToSkip -->
      </class> <!-- tests.skip -->
      <class name="tests.pass">
        <test-method status="PASS" signature="setUp(java.lang.String)[pri:0, instance:tests.pass@2b662a77]" name="setUp" is-config="true" duration-ms="2704" started-at="2018-02-28T00:08:09Z" finished-at="2018-02-28T00:08:12Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[ch]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="readFromXl()[pri:0, instance:tests.pass@2b662a77]" name="readFromXl" duration-ms="169" started-at="2018-02-28T00:08:12Z" finished-at="2018-02-28T00:08:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- readFromXl -->
        <test-method status="PASS" signature="writeIntoXl()[pri:0, instance:tests.pass@2b662a77]" name="writeIntoXl" duration-ms="1254" started-at="2018-02-28T00:08:12Z" finished-at="2018-02-28T00:08:13Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- writeIntoXl -->
        <test-method status="PASS" signature="teardown()[pri:0, instance:tests.pass@2b662a77]" name="teardown" is-config="true" duration-ms="137" started-at="2018-02-28T00:08:13Z" finished-at="2018-02-28T00:08:14Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- teardown -->
      </class> <!-- tests.pass -->
      <class name="tests.fail">
        <test-method status="FAIL" signature="readFromXl()[pri:0, instance:tests.fail@5c33f1a9]" name="readFromXl" duration-ms="1" started-at="2018-02-28T00:08:13Z" finished-at="2018-02-28T00:08:13Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at utils.webDriverApi.typeByXpath(webDriverApi.java:15)
	at tests.fail.readFromXl(fail.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- readFromXl -->
        <test-method status="FAIL" signature="writeIntoXl()[pri:0, instance:tests.fail@5c33f1a9]" name="writeIntoXl" duration-ms="1" started-at="2018-02-28T00:08:13Z" finished-at="2018-02-28T00:08:13Z">
          <exception class="java.lang.NullPointerException">
            <full-stacktrace>
              <![CDATA[java.lang.NullPointerException
	at tests.fail.writeIntoXl(fail.java:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.NullPointerException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- writeIntoXl -->
      </class> <!-- tests.fail -->
    </test> <!-- chrome test -->
    <test name="fireFox test" duration-ms="0" started-at="2018-02-28T05:08:14Z" finished-at="2018-02-28T05:08:14Z">
    </test> <!-- fireFox test -->
  </suite> <!-- testNG Framework -->
</testng-results>
